name: pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v1.0.0
    with:
      examples: |
        [
          { "example": "examples/accounts/example.yaml" },
          { "example": "examples/accounts/example.yaml", "observed_resources": "examples/observed-resources/step-1" }
        ]
      api_path: apis/accounts
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v1.0.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e-aws.yaml@v1.0.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  publish:
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v1.0.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
